### ISSUE TITLE
Error Exception code aws media insight content localization

### ISSUE THREAD

**Issue by jonathanknightceo** [aws-solutions/aws-media-insights-content-localization#216] opened 2021-10-19 00:37 UTC
Hi

I try deploy this in Ireland region. When this try to deploy in Ireland region I always see this screen when I log in. Is there way to fix this?

![image](https://user-images.githubusercontent.com/92765505/137824885-f66d7f66-da3e-4295-9568-3648ffdebc66.png)

```Dataplane Error. Please check browser and dataplane logs.```
Do you plan on supporting Asian regions in future? I am in Japan. 
Looking at AWS website Ireland is the closest to Japan out of the 3 regions you support.

**Comment by jonathanknightceo** [comment] 2021-10-19 00:38
I used the link that is on the main page that says Cloud Formation launch.

Jonathan Knight - CEO - Hachidori, Inc.

**Comment by aburkleaux-amazon** [comment] 2021-10-19 19:30
I tested the Ireland deployment link on the default branch (development) for this repository and was not able to reproduce the issue you encountered.  This is the uri that loaded in the cloudformation console when I clicked on the **Launch Stack** link for Ireland: 

https://rodeolabz-eu-west-1.s3.eu-west-1.amazonaws.com/aws-content-localization/v0.1.0/aws-content-localization.template

Here are a few things to check to help provide more information:

1. Verify the uri matches the one I tested above.
2. Occasionally, I have noticed in Ireland that the CloudFront distribution may not be fully available when the stack completes.  This is usually resolved within an hour of the deployment.  Wait and retry the app after an hour or so after deployment.
3. Use your browsers debugger to observer the API requests and check if there are any errors reported from API calls (especially the MIE dataplane).
4. Try the deployment in another region to see if you have the same error.

Regarding support for other regions...this project _should_ work in regions that support the underlying AWS services.  However, we haven't tested in ap-northeast-1 yet.  You can build a package for a different region by following the instructions in the [Building from source code section ](https://github.com/aws-solutions/aws-media-insights-content-localization#building-the-solution-from-source-code)of the README.

**Closed** 2021-12-29 21:46 UTC
