### ISSUE TITLE
Add test of one-click deploy to release workflow

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#168] opened 2021-09-16 18:12 UTC
The PR workflow and the scheduled workflow test the two part "developer-style" deploy of Content Localization because, there may be dependencies between the development branch of MIE as new features are added.

**Comment by ianwow** [comment] 2021-12-29 21:39
duplicate of #106

**Closed by ianwow** 2021-12-29 21:39 UTC
